fruits = []
f1 = input("Enter 1st Fruit: ")
fruits.append(f1)
f2 = input("Enter 2nd Fruit: ")
fruits.append(f2)
f3 = input("Enter 3rd Fruit: ")
fruits.append(f3)
f4 = input("Enter 4th Fruit: ")
fruits.append(f4)
f5 = input("Enter 5th Fruit: ")
fruits.append(f5)
f6 = input("Enter 6th Fruit: ")
fruits.append(f6)
f7 = input("Enter 7th Fruit: ")
fruits.append(f7)
print(fruits)