marks = []
s1 = int(input("Enter Student 1's marks: "))
marks.append(s1)
s2 = int(input("Enter Student 2's marks: "))
marks.append(s2)
s3 = int(input("Enter Student 3's marks: "))
marks.append(s3)
s4 = int(input("Enter Student 4's marks: "))
marks.append(s4)
s5 = int(input("Enter Student 5's marks: "))
marks.append(s5)
s6 = int(input("Enter Student 6's marks: "))
marks.append(s6)

marks.sort()
print(marks)