s = set()
a = int(input("Enter a Number: "))
s.add(a)
a = int(input("Enter a Number: "))
s.add(a)
a = int(input("Enter a Number: "))
s.add(a)
a = int(input("Enter a Number: "))
s.add(a)
a = int(input("Enter a Number: "))
s.add(a)
a = int(input("Enter a Number: "))
s.add(a)
a = int(input("Enter a Number: "))
s.add(a)
a = int(input("Enter a Number: "))
s.add(a)
print(s)